oslokommune/ok

cmd/pkg/install.go
Be more precise and clear about what actually happens when running e.g.g `ok pkg install someFolder`.
=> chore: Improve explanations in ok pkg install --help

cmd/get.go, cmd/version.go, main.go
See [GoReleaser ldlflags](https://goreleaser.com/cookbooks/using-main.version/).
> By default, GoReleaser will set the following 3 ldflags:
main.version: Current Git tag (the v prefix is stripped) or the name of the snapshot, if you're using the --snapshot flag
main.commit: Current git commit SHA
main.date: Date in the [RFC3339](https://pkg.go.dev/time#pkg-constants) format
This in turn sets`version`, `commit` and `date` variables:
https://github.com/oslokommune/ok/blob/af8801f19792b30adaee754926f4ec591a87cb53/main.go#L11
This can be tested locally:
```sh
go build -ldflags "-X main.version=1.0.0 -X main.commit=abc1234 -X main.date=$(date +%Y-%m-%dT%H:%M:%SZ)" -o ok .
./ok version
Version: 1.0.0
Date:    2024-07-17T12:07:21Z
Commit:  abc1234
```
`ok version` should match the actual …
=> feat: Use version from Goreleaser

pkg/pkg/common/manifest.go, pkg/pkg/install/install.go, pkg/pkg/install/install_test.go, pkg/pkg/install/testdata/packages-github-actions.yml
This is a proof of concept for a simple way to supporting github actions templates. We can discuss other designs / variable namings before applying. Some designs are discussed in https://github.com/oslokommune/golden-path-boilerplate/issues/339.
We might want more advanced capabilities later, but right now I wanted to keep things simple.
---
Design question: Should line 1 in the file below always be required, or should it default to `boilerplate/terraform`?
https://github.com/oslokommune/ok/blob/96793563334be8a7052b12e436c17877491b4527/pkg/pkg/install/testdata/packages-github-actions.yml#L1
Given above example, `ok` will use this template URL:
The value refer to a directory under `https://github.com/oslokommune/golden-path-boilerplate/tree/main/boilerplate/github-actions`.
Currently, if …
=> feat: Add DefaultTemplatePathPrefix

go.mod, go.sum, pkg/pkg/install/install.go, pkg/pkg/install/install_test.go, pkg/pkg/install/testdata/package.yml
`BASE_URL` does not support local file system right now. It did a little while ago, but then it didn't support remote file systems. This PR fix so `ok` supports both.
Boilerplate interprets whether `--template-url` is file or URL. Then `ok pkg` must also do it, unless we are going to support extra arguments like `--use-file-system`. Since it's not very difficult, I chose to go the Boilerplate way now.
Fixes https://github.com/oslokommune/ok/issues/181.
* Support file system and URLs for BASE_URL.
* Simplicity for the user
=> fix: Support both path and url for BASE_URL

cmd/pkg/install.go
Noticed that the example message in ok pkg install lacked the word "pkg" - might as well fix it..
=> docs: Fix help message for ok pkg install

cmd/version.go, pkg/pkg/githubreleases/githubreleases.go
```sh
go run -ldflags "-X main.version=1.0.0 -X main.commit=abc1234 -X main.date=$(date +%Y-%m-%dT%H:%M:%SZ)" ../main.go version
```
Using old version:
```
Version: 1.0.0
Date:    2024-08-28T14:51:26Z
Commit:  abc1234
A new release of ok is available: 1.0.0 → 3.3.1
To update, run the following commands:
brew update
brew upgrade ok
For other update methods, see https://km.oslo.systems/setup/before-you-start/tools/ok/#updating
```
Using the latest version:
```sh
go run -ldflags "-X main.version=3.3.1 -X main.commit=abc1234 -X main.date=$(date +%Y-%m-%dT%H:%M:%SZ)" ../main.go version
```
```
Version: 3.3.1
Date:    2024-08-28T14:54:57Z
Commit:  abc1234
You are using the latest version.
```
=> feat: Add update check when running ok version

.goreleaser.yml, cmd/pkg/add.go, cmd/pkg/common.go, cmd/pkg/install.go, cmd/pkg/update.go, scripts/completions.sh
Support tab-completion for
- `ok pkg add` *tab* to see all available github releases
- `ok pkg update` *tab* to see all output folders in your packages.yml
- `ok pkg install` *tab* to see all output folders in your packages.yml
This does not automatically apply tab-completions in your shell.
It is possible to let brew install this completion script for you, but I have not yet had time to look into that.
~For now you have the ability to source the completions directly in the terminal session.~
I made an attempt at installing completions by default
- [.goreleaser generate completions](https://github.com/oslokommune/ok/pull/208/commits/fcb599e3d89d1e53dafb96c639eb3229f256fe5a#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689R7)
- [.goreleaser bundle completion …
=> feat: ok pkg tab-completions

.gitignore, cmd/docs.go, docs-optimizer/.gitignore, docs-optimizer/index.js, docs-optimizer/package-lock.json, docs-optimizer/package.json, go.mod, go.sum, magefiles/magefile.go
feat: Add docs command to generate Markdown documentation
Will use this to put docs on https://km.oslo.systems/
Employs a Magefile to regenerate docs and execute a separate JavaScript script. This script uses Remark to parse the Markdown through an AST, enhancing documentation by adding code block language tags, adjusting heading levels, and renaming certain headings. After that, it is run through Prettier.
=> feat: Add docs command to generate Markdown documentation

.goreleaser.yml
GoReleaser klager over uspesifisert versjon i `.goreleaser` konfigurasjon.
Se logger her: https://github.com/oslokommune/ok/actions/runs/10772486725/job/29870241049#step:4:17
Legger til versjon samt referanse til jsonschema i konfigurasjonsfil.
=> ci: specify goreleaser config version and schema

pkg/pkg/config/schema.go
Put schema files in separate dir. We can change dir to something else later if somebody has any opinions.
Clean up. Better DX. Less file clutter.
=> feat: Put schemas in separate dir

pkg/aws/admin-session.go
If you have a shell config without line feed at the end of the file, the appended line would follow the last line. Fix this by adding an empty line before adding actual content.
=> fix: Fix bug when missing line feed on last line

cmd/aws/exec.go, pkg/aws/exec.go
Move from trying to execute `/bin/sh` via go-code to build up a command that the user can use to connect to the ECS task using the AWS tools that are built to handle this.
Example usage:
```
ok aws ecs-exec
>> To execute command on the container, run the following:
aws ecs execute-command --cluster arn:aws:ecs:eu-west-1:932360772598:cluster/pirates-dev --task arn:aws:ecs:eu-west-1:932360772598:task/pirates-dev/942649740a2c419caa00dd279ab51e4a --container too-tikki --command "/bin/sh" --interactive
```
User copies the `aws ecs execute-command` line and the `aws` CLI tool deals with session manager and handling the connection to the ECS task
The user can then change the command if need be:
```
aws ecs execute-command --cluster arn:aws:ecs:eu-west-1:932360772598:cluster/pirates-dev --task …
```
=> fix: output command to connect to ECS task instead of trying to execute it in go-code

pkg/aws/admin-session.go
Some users sometimes experience `ForbiddenException`. When that happens, a new login attempt is usually working. We have investigated and have not found any pattern. The theory is that the group membership is not completely propagated in AWS, and that users still get a stale state.
Adding tip how to solve it:
=> feat: Add more details about ForbiddenException

pkg/pkg/add/add.go, pkg/pkg/schema/schema.go, pkg/pkg/update/update.go, pkg/pkg/update/update_test.go
Fixes bug introduced by #341: When running `ok pkg install -i` or `ok pkg install something`, and selecting fewer packages than in the package manifest, `ok` replaces all packages in the manifest with the selected packages. They should not be deleted.
The changes to `add` and `schema` dirs improves readability of slightly related code that I also used while debugging.
Add e2e tests to ensure we don't introduce bugs when we do core rewrites like in #341.
=> fix: Keep existing packages when updating a subset

pkg/pkg/update/migrate_config/metadata/json_schema.go, pkg/pkg/update/update.go
Fixes this:
```sh
$ ok pkg update rds-bastion
Updating schema configuration files: rds-bastionupdating packages: parsing first line of file '_config/rds-bastion.yml': parsing metadata from line '# yaml-language-server: $schema=.schemas/rds-bastion-v3.4.0.schema.json': creating semver: Invalid Semantic Version
```
Errors:
* Cannot update templates with template name containing dash, for instance `rds-bastion`. Fixed by updating regex.
* The error gets entangled with the output. Fixed this by putting output on separate lines.
=> fix: update templates with slash

pkg/aws/admin-session.go
This is a nice to have feature, so it's totally fine to continue without failure.
=> fix: Improve error handling on login code notification

.run/mage test.run.xml, cmd/pkg/add.go, cmd/pkg/testdata/bump-ref-field/expected/config/app-hello.yml, cmd/pkg/testdata/bump-ref-field/expected/config/common-config.yml, cmd/pkg/testdata/bump-ref-field/input/json-schemas/app-v9.0.0.schema.json, cmd/pkg/testdata/bump-ref-field/input/json-schemas/load-balancing-alb-v4.0.0.schema.json, cmd/pkg/testdata/bump-schema-version/expected/config/app-hello.yml, cmd/pkg/testdata/bump-schema-version/expected/config/common-config.yml, cmd/pkg/testdata/bump-schema-version/expected/packages.yml, cmd/pkg/testdata/bump-schema-version/input/boilerplate/terraform/app/boilerplate.yml, cmd/pkg/testdata/bump-schema-version/input/config/app-hello.yml, cmd/pkg/testdata/bump-schema-version/input/config/common-config.yml, cmd/pkg/testdata/bump-schema-version/input/json-schemas/app-v9.0.0.schema.json, cmd/pkg/testdata/bump-schema-version/input/json-schemas/load-balancing-alb-v4.0.0.schema.json, cmd/pkg/testdata/bump-schema-version/input/packages.yml, cmd/pkg/update.go, cmd/pkg/update_test.go, cmd/root.go, pkg/pkg/add/add.go, pkg/pkg/common/package.go, pkg/pkg/common/schema_generator.go, pkg/pkg/schema/schema.go, pkg/pkg/update/update.go, pkg/pkg/update/update_test.go
When running `ok pkg update`, the json schema declaration gets set to the _current_ version of the template version. For instance, given current package version is 8.0.4, and new version is 9.0.0:
After running `ok pkg update`, the var file look like this:
```yaml
```
when it should look like this
```yaml
```
The important commit is this: https://github.com/oslokommune/ok/pull/375/commits/4693f571dd1e1af86b7b3b9caa28536e26b784a6
The rest are for fixing tests and refactorings.
Make sure the function `updateSchemaConfiguration` gets the update packages, not the original ones. This fixes the bug because this function writes the json schema declaration to the var file.
```
selectedPackages = updatedSelectedPackages
```
fixes a bug where old json schema version gets written to a var file.
=> fix: `ok pkg update` writes old template version to var file

cmd/aws/generate.go, cmd/root.go, pkg/aws/config/assets/callback_result.html, pkg/aws/config/doc.go, pkg/aws/config/generate.go, pkg/aws/config/generate_test.go, pkg/aws/config/sso.go, pkg/aws/config/types.go
Proposal for a new command in okcli that allows a user to generate AWS CLI configuration for all accounts and roles they have access to through AWS IAM Identity Center.
Example usage: `ok aws generate --sso-start-url "https://example.awsapps.com/start" --sso-region "us-east-1"`
=> feat: add cli command for generating aws cli config

pkg/aws/config/generate.go, pkg/aws/config/generate_test.go, pkg/aws/config/sso.go
This allows users of the CLI to more easily redirect the AWS CLI config to a file.
=> fix: output diagnostics to standard error

cmd/pkg/install.go, cmd/pkg/recursive.go, cmd/pkg/testdata/update/recursive/expected/app-common/config.yml, cmd/pkg/testdata/update/recursive/expected/app-common/packages.yml, cmd/pkg/testdata/update/recursive/expected/app-hello/config.yml, cmd/pkg/testdata/update/recursive/expected/app-hello/packages.yml, cmd/pkg/testdata/update/recursive/expected/common-config.yml, cmd/pkg/testdata/update/recursive/input/root/app-common/config.yml, cmd/pkg/testdata/update/recursive/input/root/app-common/packages.yml, cmd/pkg/testdata/update/recursive/input/root/app-hello/config.yml, cmd/pkg/testdata/update/recursive/input/root/app-hello/packages.yml, cmd/pkg/testdata/update/recursive/input/root/common-config.yml, cmd/pkg/update.go, cmd/pkg/update_test.go, pkg/pkg/update/migrate_config/migrate.go, pkg/pkg/update/update.go, pkg/pkg/update/update_test.go
#391 added `ok pkg install --recursive`, now doing the same for `ok pkg update`.
It makes sense for the `update` command to behave similarly as `install`.
=> feat: Add `--recursive` for `ok pkg update`

cmd/pk.go, cmd/pk/install.go, cmd/root.go, go.mod, go.sum, pkg/pk/common.go, pkg/pk/types.go
This assumes the config will look like what's in https://github.com/oslokommune/ok/issues/418, but that can be changed (later). It does not matter at this point. It matters when we move this command over to `ok pkg` instead of having it named `ok pk` and hidden behind the experimental flag.
Commits will be squashed.
```
export OK_ENABLE_EXPERIMENTAL=true
go run main.go pk install --dry-run
go run main.go pk install
```
Looks for configs in `.ok` and runs Boilerplate commands based on the contents. 
Plan:
We release this and test it in `pirates-iac`.
=> Add `ok pk install` experimental subcommand for new package file format

cmd/pkg/add.go, pkg/pkg/add/add.go, pkg/pkg/add/add_test.go, pkg/pkg/common/common.go, pkg/pkg/common/common_test.go, pkg/pkg/common/save_manifest.go
An attempt to introduce a new default location of `packages.yml`, as well as package configuration file, when using `ok pkg add` while being backwards-compatible with the old location.
Example old structure for `stacks/dev`:
- `stacks/dev/packages.yml`
- `stacks/dev/_config/common-config.yml`
- `stacks/dev/_config/app-example.yml`
Example new structure for `stacks/dev`:
- `stacks/dev/common-config.yml`
- `stacks/dev/app-example/config.yml`
- `stacks/dev/app-example/packages.yml`
The new behavior of `ok pkg add` is as follows:
- If the current working directory contains a `packages.yml` and a `_config` directory, we fall back to the old behavior.
- If the current working directory contains a `packages.yml` and the key `DefaultPackagePathPrefix` is set to `boilerplate/github-actions`, we …
=> feat: update default location of package manifest and var files

.github/workflows/release.yml
This is needed to properly create GitHub and Homebrew releases when a release-please PR has been merged (e.g., https://github.com/oslokommune/ok/pull/431).
(We can optionally consider removing the `paths` argument from the workflow in its entirety or perhaps add a comment on why it's there in the first place)
=> ci: trigger release on changes from release please

cmd/root.go, cmd/root_test.go
Før:
Litt før dette hadde vi:
Med denne PR-en:
https://oslokommune.slack.com/archives/CV9EGL9UG/p1741267437944039
Forhåpentligvis forbedret UX:
* Gjør det litt tydelige at det har skjedd en feil
* Gjør feilmeldingen lettere å lese
Closes [#2261](https://github.com/oslokommune/golden-path-iac/issues/2261)
=> feat: Pretty print errors
